version: 2

jobs:
  build_test_deploy:
    docker:
      - image: circleci/node:10.7.0
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - run: sudo npm update -g
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "d5:04:e9:cb:15:04:3e:74:ab:10:1f:3f:7b:28:11:0f"
      - run: ./deploy.sh

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build_test_deploy
